---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":github:"
    groups:
      actions:
        patterns:
          - "*"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":whale:"
    groups:
      actions:
        patterns:
          - "*"

  # Maintain dependencies for go
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":seedling:"
