stages:
   - create
   - test
   - tag-release

.docker_template: 
  image: docker:stable
  tags:
    - dind
  services:
    - docker:stable-dind
  cache: {}
  dependencies: []
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
    DOCKER_TAG: $CI_COMMIT_SHA
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_JOB_TOKEN" "$CI_REGISTRY"
  
build-image:
  extends: .docker_template
  stage: create
  script:
    - docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} .
    - docker push "${DOCKER_IMAGE}:${DOCKER_TAG}"

test-image:
  extends: .docker_template
  stage: test
  image:
    name: ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}:${DOCKER_TAG}
  before_script: []
  script:
    - kubectl version --short --client
    - helm version --client
    - aws-iam-authenticator help
    - aws --version
    - echo "Everything Looks fine"

tagged-image:
  extends: .docker_template
  stage: tag-release
  script:
    - echo "Pulling Docker image..."
    - export IMAGE_TO_TAG=${DOCKER_IMAGE}:${DOCKER_TAG}
    - docker pull ${IMAGE_TO_TAG}
    - echo "Tagging image"
    - export TAGGED_IMAGE="${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}"
    - docker tag ${IMAGE_TO_TAG} ${TAGGED_IMAGE}
    - docker tag ${IMAGE_TO_TAG} ${CI_REGISTRY_IMAGE}:latest
    - echo "Pushing to GitLab Container Registry..."
    - docker push ${TAGGED_IMAGE}
    - docker push ${CI_REGISTRY_IMAGE}:latest
  only:
    - /^v[\d\.]+$/