---
apiVersion: v1
kind: Namespace
metadata:
  name: moulick-test
  labels:
    istio-injection: enabled
    moulick: "true"
---
apiVersion: v1
kind: Pod
metadata:
  name: moulick-debug
  namespace: moulick-test
  labels:
    name: moulick-debug
    moulick: "true"
spec:
  containers:
    - name: debug
      image: moulick/debug-image:latest
      imagePullPolicy: Always
      resources:
        limits:
          cpu: "1"
          memory: 2G
        requests:
          cpu: "1"
          memory: 2G
      args:
        - /bin/bash
        - -c
        - "trap : TERM INT; sleep infinity & wait"
      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      ports:
        - containerPort: 80
    - name: dind
      image: docker:stable-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      resources:
        limits:
          cpu: 2G
          memory: 2G
        requests:
          cpu: 100m
          memory: 100Mi
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
  volumes:
    - name: dind-storage
      emptyDir: {}
