apiVersion: v1
kind: Pod
metadata:
  name: moulick-debug
  labels:
    name: moulick-debug
spec:
  containers:
    - name: debug
      image: moulick/debug-image:v2
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 2G
          memory: 2G
        requests:
          cpu: 100m
          memory: 100Mi
      args:
        - /bin/bash
        - -c
        - sleep 10000000000
      ports:
        - containerPort: 80
      volumeMounts:
        - name: dockersock
          mountPath: "/var/run/docker.sock"
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
