apiVersion: v1
kind: Pod
metadata:
  name: moulick-debug
  labels:
    name: moulick-debug
spec:
  containers:
    - name: debug
      image: moulick/debug-image:v2.5
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 
          memory: 10Gi
        requests:
          cpu: 100m
          memory: 10Gi
      args:
        - /bin/sh
        - -c
        - sleep 100000000
      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      ports:
        - containerPort: 80
    - name: dind
      image: docker:stable-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      resources:
        limits:
          cpu: 2G
          memory: 2G
        requests:
          cpu: 100m
          memory: 100Mi
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
  volumes:
    - name: dind-storage
      emptyDir: {}
  terminationGracePeriodSeconds: 5
