---
apiVersion: v1
kind: Namespace
metadata:
  name: moulick-test
  labels:
    istio-injection: enabled
    moulick: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: moulick-debug
  labels:
    moulick: "true"
rules:
  - apiGroups: ["*"] # "" indicates the core API group
    resources:
      [
        "pods",
        "deployments",
        "nodes",
        "daemonset",
        "ingress",
        "service",
        "replicaset",
      ]
    verbs: ["create", "get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: moulick-debug
  namespace: moulick-test
  labels:
    moulick: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: moulick-debug
  labels:
    moulick: "true"

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: moulick-debug
subjects:
  - kind: ServiceAccount
    name: moulick-debug
    namespace: moulick-test
---
apiVersion: v1
kind: Pod
metadata:
  name: moulick-debug
  namespace: moulick-test
  labels:
    name: moulick-debug
    moulick: "true"
spec:
  serviceAccount: moulick-debug
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: moulick-debug
  containers:
    - name: debug
      image: moulick/debug-image:latest
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "1"
          memory: 2G
        limits:
          cpu: "1"
          memory: 2G
      volumeMounts:
        - name: storage
          mountPath: /storage
      args:
        - /bin/bash
        - -c
        - "trap : TERM INT; sleep infinity & wait"
      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      securityContext:
        privileged: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moulick-debug
  namespace: moulick-test
  labels:
    name: moulick-debug
    moulick: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: gp3
