---
apiVersion: v1
kind: Namespace
metadata:
  name: moulick-test
  labels:
    istio-injection: enabled
    moulick: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: moulick-debug
  labels:
    moulick: "true"
rules:
  - apiGroups: ["*"] # "" indicates the core API group
    resources:
      - pods
      - deployments
      - nodes
      - daemonset
      - ingress
      - service
      - replicaset
    verbs:
      - create
      - get
      - watch
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: moulick-debug
  namespace: moulick-test
  labels:
    moulick: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: moulick-debug
  labels:
    moulick: "true"

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: moulick-debug
subjects:
  - kind: ServiceAccount
    name: moulick-debug
    namespace: moulick-test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: moulick-debug
  namespace: moulick-test
data:
  urls.txt: |
    https://1.1.1.1
  rest-payload.json: |
    {
      "name": "moulick",
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moulick-debug
  namespace: moulick-test
  labels:
    app.kubernetes.io/component: moulick
    app.kubernetes.io/instance: moulick
    moulick: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: moulick
      app.kubernetes.io/instance: moulick
      moulick: "true"
  template:
    metadata:
      annotations:
        config.linkerd.io/proxy-cpu-limit: 200m
        config.linkerd.io/proxy-cpu-request: 100m
        config.linkerd.io/proxy-memory-limit: 200Mi
        config.linkerd.io/proxy-memory-request: 100Mi
        linkerd.io/inject: enabled
        istio.io/inject: enabled
      labels:
        app.kubernetes.io/component: moulick
        app.kubernetes.io/instance: moulick
        moulick: "true"
    spec:
      serviceAccount: moulick-debug
      volumes:
        - name: moulick-debug
          configMap:
            name: moulick-debug
        - name: cache-volume
          emptyDir:
            sizeLimit: 10Mi
      containers:
        - name: moulick-debug
          image: moulick/debug-image:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: moulick-debug
              mountPath: /etc/moulick-debug
            - mountPath: /cache
              name: cache-volume
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          command:
            - /bin/sh
            - -c
            - "trap : TERM INT; sleep 100000000000000000 & wait"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
